### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by thiefsix** [EggUncle/PtraceInject#1]
大佬，这个工程怎么编译啊，麻烦说一下详细的步骤，谢谢！

**Comment by EggUncle** [comment]
clone下来,进入repo的根目录,然后使用ndk-build就行了,ndk-build的安装教程还挺多的,你查一下看看.

**Comment by thiefsix** [comment]
我ndk已经安装好了，但是在根目录下运行报错了，我在网上找了一些解决办法，说要到jni目录下运行ndk-build,但是这个工程里面有好几个jni目录，不知道到底在哪里运行。
根目录运行报错信息如下：
oldsix@ubuntu:~/PtraceInject$ ndk-build
Android NDK: Could not find application project directory !    
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.    
/home/oldsix/android-ndk-r10b/build/core/build-local.mk:148: *** Android NDK: Aborting    .  Stop.

**Comment by EggUncle** [comment]
啊抱歉我太久没看这个repo了,它的结构大致如下
.
├── android
│   └── hidekeyinjni   这里是一个android项目,用于测试注入工具的效果
├── c
│   ├── hookerDir  这是需要对应注入的so,需要进入到这个目录进行ndk-build编译相应so
│   └── pMainDir   这是注入工具,需要进入到这个目录进行ndk-build编译相应可执行文件
└── README.md

**Comment by thiefsix** [comment]
好的，谢谢！已经解决了

**Comment by thiefsix** [comment]
大佬，你好，这个使用教程里面的so的入口函数名称是什么啊

**Comment by EggUncle** [comment]
注入函数的源码在这里, PtraceInject/c/hookerDir/jni/hooker.c ,名字为hook_entry
